local_backend: true

backend:
  name: github
  branch: main
  repo: chengjin-anbiz/decapsaurus-test-1
  squash_merges: true

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/img"
public_folder: "/img/"

collections:
# - name: blog
#   label: "Blog"
#   folder: blog
#   identifier_field: title
#   extension: md
#   create: true
#   publish: false
#   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#   fields:
#     - { name: title, label: Title, widget: string }
#     - { name: body, label: Body, widget: markdown }
#     - { name: slug, label: Slug, widget: string }
#     - label: "Tags"
#       name: "tags"
#       widget: "list"
#     - label: "Authors"
#       name: "authors"
#       widget: "list"
#       fields:
#         - { name: name, label: Name, widget: string }
#         - { name: title, label: Title, widget: string }
#         - { name: url, label: URL, widget: string }
#         - { name: imageUrl, label: ImageURL, widget: string }
- name: docs
  label: "Docs"
  folder: docs
  extension: md
  create: true
  publish: false
  nested: 
    depth: 100
    summary: "{{title}}"
    subfolders: false  
  meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  fields:
    - label: "ID"
      name: "id"
      widget: "string"
      required: false
      hint: "Optional. Defaults to file path if not set."
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Sidebar Label"
      name: "sidebar_label"
      widget: "string"
      required: false
    - label: "Description"
      name: "description"
      widget: "text"
      required: false
    - label: "Body"
      name: "body"
      widget: "markdown"